#!/usr/bin/env bash

set -e

bin/pulsar initialize-cluster-metadata --cluster cluster-a --zookeeper zookeeper:2181 --configuration-store zookeeper:2181  --web-service-url http://broker:8080 --broker-service-url pulsar://broker-1:6650
