#!/usr/bin/env bash

set -e


for i in $(seq 1 1000);
do
    docker container restart pulsar-scheduled-exception-repro-broker-1-1
    sleep 5
    docker container restart pulsar-scheduled-exception-repro-broker-2-1
    sleep 5
    docker container restart pulsar-scheduled-exception-repro-broker-3-1
    sleep 5
done
